name: ai_vocabulary
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  im_charts:
    path: im_charts
  text2speech:
    path: text2speech
  speech_record:
    path: speech_record
  cupertino_icons: ^1.0.8
  flutter_platform_widgets: ^7.0.1
  http: ^1.2.2
  azlistview: ^2.0.0
  path_provider: ^2.1.5
  sqlite3: ^2.4.7
  transparent_image: ^2.0.1
  dotted_line: ^3.2.3
  flutter_spinkit: ^5.2.1
  intl: ^0.20.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_web_frame: ^1.0.0
  flutter_lorem: ^2.0.0

dart_code_metrics:
  rules:
    - always-remove-listener
    - avoid-undisposed-instances:
    - avoid-unassigned-stream-subscriptions

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
