import 'model/vocabulary.dart';

const apple_json =
    '{"word_id": 830, "word": "apple", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a hard, round fruit with a smooth green, red or yellow skin", "subscript": "countable, uncountable", "examples": ["apple juice"]}], "inflection": "apple, apples", "phonetic_uk": "/\u02c8\u00e6p.\u0259l/", "phonetic_us": "/\u02c8\u00e6p.\u0259l/", "audio_uk": "oxfordstu://audio/apple__gb_1.mp3", "audio_us": "oxfordstu://audio/apple__us_1.mp3","translate": "\u82f9\u679c"}]}';
const record_json =
    '{"word_id": 12316, "word": "record", "asset": null, "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a written account of what has happened, been done, etc.", "subscript": "countable", "examples": ["The teachers keep records of the children\'s progress.", "medical records"]}, {"explain": "the facts, events, etc. that are known (and sometimes written down) about sb/sth", "subscript": "singular", "examples": ["The police said that the man had a criminal record (=\u2009he had been found guilty of crimes in the past).", "This airline has a bad safety record."]}, {"explain": "a thin, round piece of plastic which can store music so that you can play it when you want", "subscript": "countable", "examples": []}, {"explain": "the best performance or the highest or lowest level, etc. ever reached in sth, especially in sport", "subscript": "countable", "examples": ["He did it in record time (=\u2009very fast).", "She\'s hoping to break the record for the 100 metres.", "Who holds the world record for high jump?"]}], "inflection": "record, records", "phonetic_uk": "/\u02c8rek.\u0254\u02d0d/", "phonetic_us": "/\u02c8rek.\u025ad/", "audio_uk": "oxfordstu://audio/record__gb_1.mp3", "audio_us": "oxfordstu://audio/record__us_1.mp3"}, {"part_of_speech": "verb", "explanations": [{"explain": "to write down or film facts or events so that they can be referred to later and will not be forgotten", "subscript": "transitive", "examples": ["At the inquest the coroner recorded a verdict of accidental death.", "He recorded everything in his diary."]}, {"explain": "to put music, a film, a programme, etc. onto a CD or cassette so that it can be listened to or watched again later", "subscript": "intransitive, transitive", "examples": ["Quiet, please! We\'re recording.", "The band has recently recorded a new album.", "There\'s a concert I would like to record from the radio this evening."]}], "inflection": "record, records, recording, recorded, recorded", "phonetic_uk": "/r\u026a\u02c8k\u0254\u02d0d/", "phonetic_us": "/r\u026a\u02c8k\u0254\u02d0rd/", "audio_uk": "oxfordstu://audio/record__gb_2.mp3", "audio_us": "oxfordstu://audio/record__us_2.mp3"}]}';
const abdomen_json =
    '{"word_id": 16, "word": "abdomen", "asset": "oxfordstu://img/thumb/insects_wp3.jpg", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a part of your body below the chest that contains the stomach, bowels, etc.", "subscript": "(anatomy)countable", "examples": []}, {"explain": "the end part of an insect\'s body", "subscript": "(biology)countable", "examples": []}], "inflection": "abdomen, abdomens", "phonetic_uk": "/\u02c8\u00e6b.d\u0259.m\u0259n/", "phonetic_us": "/\u02c8\u00e6b.d\u0259.m\u0259n/", "audio_uk": "oxfordstu://audio/abdomen__gb_1.mp3", "audio_us": "oxfordstu://audio/abdomen__us_1.mp3"}, {"part_of_speech": "adjective", "explanations": [{"explain": "abdominal", "subscript": null, "examples": ["abdominal pains"]}], "inflection": null, "phonetic_uk": "/\u00e6b\u02c8d\u0251m\u026an(\u0259)l/", "phonetic_us": "/\u00e6b\u02c8d\u0251m\u026an(\u0259)l/", "audio_uk": "oxfordstu://audio/abdominal__gb_1.mp3", "audio_us": "oxfordstu://audio/abdominal__us_1.mp3"}]}';

final apple = Vocabulary.fromRawJson(apple_json);
final record = Vocabulary.fromRawJson(record_json);
final abdomen = Vocabulary.fromRawJson(abdomen_json);
