import 'model/vocabulary.dart';
import 'dart:convert';

const baseUrl = 'http://www.cia1099.cloudns.ch/dict/dictionary/';
const apple_json =
    '{"word_id": 810, "frequency": 0.5, "word": "apple", "asset": "http://www.cia1099.cloudns.ch/dict/dictionary/img/thumb/apple.jpg", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a hard, round fruit with a smooth green, red or yellow skin", "subscript": "countable, uncountable", "examples": ["apple juice"]}], "audio_us": "http://www.cia1099.cloudns.ch/dict/dictionary/audio/apple__us_1.mp3", "phonetic_uk": "/\u02c8\u00e6p.\u0259l/", "inflection": "apple, apples", "phonetic_us": "/\u02c8\u00e6p(\u0259)l/", "synonyms": null, "antonyms": null, "audio_uk": "http://www.cia1099.cloudns.ch/dict/dictionary/audio/apple__gb_1.mp3", "definition_id": 992}]}';
const record_json = '''
{"word_id": 12108, "frequency": 0.9, "word": "record", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a written account of what has happened, been done, etc.", "subscript": "countable", "examples": ["The teachers keep records of the children's progress.", "medical records"]}, {"explain": "the facts, events, etc. that are known (and sometimes written down) about sb/sth", "subscript": "singular", "examples": ["The police said that the man had a criminal record (=\u2009he had been found guilty of crimes in the past).", "This airline has a bad safety record."]}, {"explain": "a thin, round piece of plastic which can store music so that you can play it when you want", "subscript": "countable", "examples": []}, {"explain": "the best performance or the highest or lowest level, etc. ever reached in sth, especially in sport", "subscript": "countable", "examples": ["Who holds the world record for high jump?", "She's hoping to break the record for the 100 metres.", "He did it in record time (=\u2009very fast)."]}, {"explain": "to say sth publicly or officially so that it may be written down and repeated", "subscript": "countable", "examples": ["He didn't want to go on the record as either praising or criticizing the proposal."]}, {"explain": "if you tell sb sth off the record, it is not yet official and you do not want it to be repeated publicly", "subscript": "countable", "examples": ["She told me off the record that she was going to resign."]}, {"explain": "to correct a mistake by telling sb the true facts", "subscript": "countable", "examples": []}], "audio_us": "oxfordstu://audio/record__us_1.mp3", "synonyms": null, "antonyms": null, "phonetic_uk": "/\u02c8rek.\u0254\u02d0d/", "audio_uk": "oxfordstu://audio/record__gb_1.mp3", "phonetic_us": "/\u02c8rek\u0259rd/", "inflection": "record, records", "definition_id": 15159}, {"part_of_speech": "verb", "explanations": [{"explain": "to write down or film facts or events so that they can be referred to later and will not be forgotten", "subscript": "transitive", "examples": ["He recorded everything in his diary.", "At the inquest the coroner recorded a verdict of accidental death."]}, {"explain": "to put music, a film, a programme, etc. onto a CD or cassette so that it can be listened to or watched again later", "subscript": "intransitive, transitive", "examples": ["Quiet, please! We're recording.", "The band has recently recorded a new album.", "There's a concert I would like to record from the radio this evening."]}], "audio_us": "oxfordstu://audio/record__us_2.mp3", "synonyms": "catalog, catalogue, enroll, enrol, enter, index, inscribe, list, put down, register, schedule, slate", "antonyms": null, "phonetic_uk": "/r\u026a\u02c8k\u0254\u02d0d/", "audio_uk": "oxfordstu://audio/record__gb_2.mp3", "phonetic_us": "/r\u026a\u02c8k\u0254rd/", "inflection": "record, records, recording, recorded, recorded", "definition_id": 15160}]}
''';

const abdomen_json = '''
{"word_id": 15, "frequency": 0.5, "word": "abdomen", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a part of your body below the chest that contains the stomach, bowels, etc.", "subscript": "(anatomy)countable", "examples": []}, {"explain": "the end part of an insect's body", "subscript": "(biology)countable", "examples": []}], "audio_us": "oxfordstu://audio/abdomen__us_1.mp3", "inflection": "abdomen, abdomens", "audio_uk": "oxfordstu://audio/abdomen__gb_1.mp3", "phonetic_us": "/\u02c8\u00e6bd\u0259m\u0259n/", "antonyms": null, "synonyms": "belly, breadbasket, gut, solar plexus, stomach, tummy", "phonetic_uk": "/\u02c8\u00e6b.d\u0259.m\u0259n/", "definition_id": 17}, {"part_of_speech": "adjective", "explanations": [{"explain": "abdominal", "subscript": null, "examples": ["abdominal pains"]}], "audio_us": "oxfordstu://audio/abdominal__us_1.mp3", "inflection": null, "audio_uk": "oxfordstu://audio/abdominal__gb_1.mp3", "phonetic_us": "/\u00e6b\u02c8d\u0251m\u026an(\u0259)l/", "antonyms": null, "synonyms": null, "phonetic_uk": null, "definition_id": 18}]}
''';
const drunk_json = '''
{"word_id": 4753, "frequency": 0.7, "word": "drink", "definitions": [{"part_of_speech": "verb", "explanations": [{"explain": "to take liquid into your body through your mouth", "subscript": "intransitive, transitive", "examples": ["Would you like anything to drink?", "We sat drinking coffee and chatting for hours."]}, {"explain": "to drink alcohol", "subscript": "intransitive, transitive", "examples": ["I never drink and drive so I'll have an orange juice.", "What do you drink \u2013 beer or wine?", "Her father used to drink heavily but he's teetotal now."]}, {"explain": "to wish sb/sth good luck by holding your glass up in the air before you drink", "subscript": "intransitive, transitive", "examples": ["We all drank to the future of the bride and groom."]}, {"explain": "to finish drinking sth", "subscript": "intransitive, transitive", "examples": ["Drink up your tea \u2013 it's getting cold."]}], "phonetic_uk": "/dr\u026a\u014bk/", "synonyms": "belt (down), gulp, guzzle, hoist, imbibe, knock back, pound (down), quaff, sip, slug (down), slurp, sup, swig, swill, toss (down or off)", "audio_uk": "oxfordstu://audio/drink__gb_1.mp3", "phonetic_us": "/dr\u026a\u014bk/", "antonyms": null, "audio_us": "oxfordstu://audio/drink__us_1.mp3", "inflection": "drink, drinks, drinking, drank, drunk", "definition_id": 5918}, {"part_of_speech": "noun", "explanations": [{"explain": "liquid for drinking", "subscript": "countable, uncountable", "examples": ["Can I have a drink please?", "a drink of milk", "soft drinks  (=\u2009cold drinks without alcohol)"]}, {"explain": "alcoholic drink", "subscript": "countable, uncountable", "examples": ["He's got a drink problem.", "Shall we go for a drink?"]}], "phonetic_uk": "/dr\u026a\u014bk/", "synonyms": "alcohol, inebriant, intoxicant, liquor, moonshine, spirits", "audio_uk": "oxfordstu://audio/drink__gb_1.mp3", "phonetic_us": "/dr\u026a\u014bk/", "antonyms": "nonintoxicant", "audio_us": "oxfordstu://audio/drink__us_1.mp3", "inflection": "drink, drinks", "definition_id": 5919}]}
''';
const phrase_drink =
    '[{"frequency": null, "phrase": "drink someone under the table", "definitions": [{"part_of_speech": "verb", "explanations": [{"explain": "to drink more alcohol than someone else without becoming as drunk as they do", "subscript": null, "examples": ["She could drink all the men under the table."]}], "inflection": "drink, drinks, drinking, drank, drunk"}], "phrase_id": 2104}, {"frequency": null, "phrase": "drink down", "definitions": [{"part_of_speech": "verb", "explanations": [{"explain": "to drink all of something, especially quickly", "subscript": "transitive", "examples": ["She made a face but drank the medicine down."]}], "inflection": "drink, drinks, drinking, drank, drunk"}], "phrase_id": 2105}, {"frequency": null, "phrase": "drink in", "definitions": [{"part_of_speech": "verb", "explanations": [{"explain": "to experience something with great enjoyment", "subscript": "transitive", "examples": ["They sat out on the terrace and drank in the stunning view."]}], "inflection": "drink, drinks, drinking, drank, drunk"}], "phrase_id": 2106}, {"frequency": null, "phrase": "drink to", "definitions": [{"part_of_speech": "verb", "explanations": [{"explain": "to wish for health, happiness, or success for someone or something, then lift your glass and drink from it", "subscript": "transitive", "examples": []}, {"explain": "used for saying that you strongly agree with what someone has said, or strongly hope that it is true", "subscript": "transitive", "examples": ["\u201cBy summer this war should be over.\u201d \u201cI\u2019ll drink to that!\u201d"]}], "inflection": "drink, drinks, drinking, drank, drunk"}], "phrase_id": 2107}, {"frequency": null, "phrase": "drink up", "definitions": [{"part_of_speech": "verb", "explanations": [{"explain": "to drink all of your drink", "subscript": "intransitive/transitive", "examples": ["Drink up, everyone, it\u2019s time to go.", "I gave the cat some milk and she drank it all up."]}], "inflection": "drink, drinks, drinking, drank, drunk"}], "phrase_id": 2108}, {"frequency": null, "phrase": "the drink", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a large area of water, especially the ocean", "subscript": null, "examples": []}], "inflection": "drink, drinks"}], "phrase_id": 2109}]';
const recommendation_json = '''
{"word_id": 12102, "frequency": 0.8, "word": "recommendation", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "saying that sth is good and should be tried or used", "subscript": "countable, uncountable", "examples": ["I visited Seville on a friend's recommendation and I really enjoyed it."]}, {"explain": "a statement about what should be done in a particular situation", "subscript": "countable", "examples": ["In their report on the crash, the committee make several recommendations on how safety could be improved."]}], "audio_us": "oxfordstu://audio/recommendation__us_1.mp3", "antonyms": null, "synonyms": null, "phonetic_uk": "/\u02ccrek.\u0259.men\u02c8de\u026a.\u0283\u0259n/", "audio_uk": "oxfordstu://audio/recommendation__gb_1.mp3", "inflection": "recommendation, recommendations", "phonetic_us": "/\u02ccrek\u0259men\u02c8de\u026a\u0283(\u0259)n/", "definition_id": 15151}]}
''';

const stage_json = '''
{"word_id": 13937, "frequency": 0.7, "word": "stage", "asset": "https://www.cia1099.cloudns.ch/dict/dictionary/img/thumb/theatre.jpg", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "one part of the progress or development of sth", "subscript": "countable", "examples": ["The first stage of the course lasts for three weeks.", "I suggest we do the journey in two stages.", "At this stage it's too early to say what will happen."]}, {"explain": "a platform in a theatre, concert hall, etc. on which actors, musicians, etc. perform", "subscript": "countable", "examples": []}, {"explain": "the world of theatre; the profession of acting", "subscript": "singular", "examples": ["Her parents didn't want her to go on the stage.", "an actor of stage and screen"]}], "audio_uk": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/stage__gb_1.mp3", "audio_us": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/stage__us_1.mp3", "inflection": "stage, stages", "antonyms": null, "phonetic_us": "/ste\\u026ad\\u0292/", "phonetic_uk": "/ste\\u026ad\\u0292/", "synonyms": "drama, dramatics, theater, theatre, theatricals, theatrics", "definition_id": 17471}, {"part_of_speech": "verb", "explanations": [{"explain": "to organize a performance of a play, concert, etc. for the public", "subscript": "(arts and media)transitive", "examples": []}, {"explain": "to organize an event", "subscript": "transitive", "examples": ["They have decided to stage a 24-hour strike."]}], "audio_uk": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/stage__gb_1.mp3", "audio_us": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/stage__us_1.mp3", "inflection": "stage, stages, staging, staged, staged", "antonyms": null, "phonetic_us": "/ste\\u026ad\\u0292/", "phonetic_uk": "/ste\\u026ad\\u0292/", "synonyms": "carry, give, mount, offer, present", "definition_id": 17472}]}
''';
const greenwash_json = '''
{"word_id": 6655, "frequency": null, "word": "greenwash", "asset": null, "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "activities by a company that are intended to make people think that it cares about the environment, even if its real business actually harms the environment", "subscript": "uncountable", "examples": []}], "audio_uk": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/greenwash__gb_1.mp3", "audio_us": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/greenwash__us_2.mp3", "inflection": null, "antonyms": null, "phonetic_us": "/\\u02c8\\u0261rin\\u02ccw\\u0251\\u0283/", "phonetic_uk": null, "synonyms": null, "definition_id": 8329}]}
''';

final apple = Vocabulary.fromRawJson(apple_json);
final record = Vocabulary.fromRawJson(record_json);
final abdomen = Vocabulary.fromRawJson(abdomen_json);
final drunk = List<Vocabulary>.from(
  json.decode(drunk_json).map((json) => Vocabulary.fromJson(json)),
);
final recommendation = Vocabulary.fromRawJson(recommendation_json);

void main() {
  print(drunk.length);
}
