import 'model/vocabulary.dart';
import 'dart:convert';

const apple_json =
    '''{"word_id": 830, "word": "apple", "asset": "http://www.cia1099.cloudns.ch/dict/dictionary/img/thumb/apple.jpg", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a hard, round fruit with a smooth green, red or yellow skin", "subscript": "countable, uncountable", "examples": ["apple juice"]}], "inflection": "apple, apples", "phonetic_uk": "/\\u02c8\\u00e6p.\\u0259l/", "phonetic_us": "/\\u02c8\\u00e6p.\\u0259l/", "audio_uk": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/apple__gb_1.mp3", "audio_us": "https://www.cia1099.cloudns.ch/dict/dictionary/audio/apple__us_1.mp3", "translate": "\\u82f9\\u679c"}]}''';
const record_json =
    '{"word_id": 12316, "word": "record", "asset": null, "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a written account of what has happened, been done, etc.", "subscript": "countable", "examples": ["The teachers keep records of the children\'s progress.", "medical records"]}, {"explain": "the facts, events, etc. that are known (and sometimes written down) about sb/sth", "subscript": "singular", "examples": ["The police said that the man had a criminal record (=\u2009he had been found guilty of crimes in the past).", "This airline has a bad safety record."]}, {"explain": "a thin, round piece of plastic which can store music so that you can play it when you want", "subscript": "countable", "examples": []}, {"explain": "the best performance or the highest or lowest level, etc. ever reached in sth, especially in sport", "subscript": "countable", "examples": ["He did it in record time (=\u2009very fast).", "She\'s hoping to break the record for the 100 metres.", "Who holds the world record for high jump?"]}], "inflection": "record, records", "phonetic_uk": "/\u02c8rek.\u0254\u02d0d/", "phonetic_us": "/\u02c8rek.\u025ad/", "audio_uk": "oxfordstu://audio/record__gb_1.mp3", "audio_us": "oxfordstu://audio/record__us_1.mp3"}, {"part_of_speech": "verb", "explanations": [{"explain": "to write down or film facts or events so that they can be referred to later and will not be forgotten", "subscript": "transitive", "examples": ["At the inquest the coroner recorded a verdict of accidental death.", "He recorded everything in his diary."]}, {"explain": "to put music, a film, a programme, etc. onto a CD or cassette so that it can be listened to or watched again later", "subscript": "intransitive, transitive", "examples": ["Quiet, please! We\'re recording.", "The band has recently recorded a new album.", "There\'s a concert I would like to record from the radio this evening."]}], "inflection": "record, records, recording, recorded, recorded", "phonetic_uk": "/r\u026a\u02c8k\u0254\u02d0d/", "phonetic_us": "/r\u026a\u02c8k\u0254\u02d0rd/", "audio_uk": "oxfordstu://audio/record__gb_2.mp3", "audio_us": "oxfordstu://audio/record__us_2.mp3"}]}';
const abdomen_json =
    '{"word_id": 16, "word": "abdomen", "asset": "oxfordstu://img/thumb/insects_wp3.jpg", "definitions": [{"part_of_speech": "noun", "explanations": [{"explain": "a part of your body below the chest that contains the stomach, bowels, etc.", "subscript": "(anatomy)countable", "examples": []}, {"explain": "the end part of an insect\'s body", "subscript": "(biology)countable", "examples": []}], "inflection": "abdomen, abdomens", "phonetic_uk": "/\u02c8\u00e6b.d\u0259.m\u0259n/", "phonetic_us": "/\u02c8\u00e6b.d\u0259.m\u0259n/", "audio_uk": "oxfordstu://audio/abdomen__gb_1.mp3", "audio_us": "oxfordstu://audio/abdomen__us_1.mp3"}, {"part_of_speech": "adjective", "explanations": [{"explain": "abdominal", "subscript": null, "examples": ["abdominal pains"]}], "inflection": null, "phonetic_uk": "/\u00e6b\u02c8d\u0251m\u026an(\u0259)l/", "phonetic_us": "/\u00e6b\u02c8d\u0251m\u026an(\u0259)l/", "audio_uk": "oxfordstu://audio/abdominal__gb_1.mp3", "audio_us": "oxfordstu://audio/abdominal__us_1.mp3"}]}';

const drunk_json = '''
[{"word_id": 4847, "word": "drink", "definitions": [{"part_of_speech": "verb", "explanations": [{"explain": "to take liquid into your body through your mouth", "subscript": "intransitive, transitive", "examples": ["We sat drinking coffee and chatting for hours.", "Would you like anything to drink?"]}, {"explain": "to drink alcohol", "subscript": "intransitive, transitive", "examples": ["Her father used to drink heavily but he's teetotal now.", "I never drink and drive so I'll have an orange juice.", "What do you drink \u2013 beer or wine?"]}], "inflection": "drink, drinks, drinking, drank, drunk", "phonetic_uk": "/dr\u026a\u014bk/", "phonetic_us": "/dr\u026a\u014bk/", "audio_uk": "oxfordstu://audio/drink__gb_1.mp3", "audio_us": "oxfordstu://audio/drink__us_1.mp3", "translate": "\u559d\u3001\u559d\u9152"}, {"part_of_speech": "noun", "explanations": [{"explain": "liquid for drinking", "subscript": "countable, uncountable", "examples": ["Can I have a drink please?", "a drink of milk", "soft drinks  (=\u2009cold drinks without alcohol)"]}, {"explain": "alcoholic drink", "subscript": "countable, uncountable", "examples": ["He's got a drink problem.", "Shall we go for a drink?"]}], "inflection": "drink, drinks", "phonetic_uk": "/dr\u026a\u014bk/", "phonetic_us": "/dr\u026a\u014bk/", "audio_uk": "oxfordstu://audio/drink__gb_1.mp3", "audio_us": "oxfordstu://audio/drink__us_1.mp3", "translate": "\u996e\u6599\uff1b\u4e00\u4efd\uff08\u996e\u6599\uff09\u3001\u9152\u7cbe\u996e\u6599\uff0c\u9152\u3001\u9152\u4f1a"}]}, {"word_id": 4875, "word": "drunk", "definitions": [{"part_of_speech": "adjective", "explanations": [{"explain": "having drunk too much alcohol", "subscript": "(not before a noun)", "examples": ["to get drunk"]}], "inflection": null, "phonetic_uk": "/dr\u028c\u014bk/", "phonetic_us": "/dr\u028c\u014bk/", "audio_uk": "oxfordstu://audio/drunk__gb_2.mp3", "audio_us": "oxfordstu://audio/drunk__us_2.mp3", "translate": "\u9189\u7684\uff0c\u559d\u9189\u7684\uff0c\u9189\u9152\u7684\u3001\u9157\u9152\u6ecb\u4e8b\uff0c\u9152\u540e\u95f9\u4e8b\u3001\u56e0\u62e5\u6709\u6743\u52bf\u800c\u98d8\u98d8\u7136"}, {"part_of_speech": "noun", "explanations": [{"explain": "drunk", "subscript": "countable", "examples": ["There were two drunks asleep under the bridge."]}], "inflection": "drunk, drunks", "phonetic_uk": "/dr\u028c\u014bk/", "phonetic_us": "/dr\u028c\u014bk/", "audio_uk": null, "audio_us": null, "translate": "\u9152\u9b3c\uff0c\u9189\u9b3c\uff0c\u9157\u9152\u8005"}]}, {"word_id": 13747, "word": "sloshed", "definitions": [{"part_of_speech": "adjective", "explanations": [{"explain": "drunk", "subscript": null, "examples": []}], "inflection": null, "phonetic_uk": "/sl\u0252\u0283t/", "phonetic_us": "/sl\u0251\u02d0\u0283t/", "audio_uk": "oxfordstu://audio/sloshed__gb_1.mp3", "audio_us": "oxfordstu://audio/sloshed__us_1.mp3", "translate": "\u559d\u9189\u7684"}]}]
''';

final apple = Vocabulary.fromRawJson(apple_json);
final record = Vocabulary.fromRawJson(record_json);
final abdomen = Vocabulary.fromRawJson(abdomen_json);
final drunk = List<Vocabulary>.from(
    json.decode(drunk_json).map((json) => Vocabulary.fromJson(json)));

void main() {
  print(drunk.length);
}
